apiVersion: v1
kind: Service
metadata:
  name: postgress-service
  labels:
    name: postgress-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 80
  selector: 
    name: postgress-deployment
