apiVersion: v1
kind: Service
metadata:
  name: radis-service
  labels:
    name: redis-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    name: redis-deployment
