apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker-deployment
  template:
    metadata:
      name: worker-deployment
      labels:
        name: worker-deployment
    spec:
      containers:
        - name: worker-deployment
          image: dockersamples/examplevotingapp_worker
  




